on: [push]

name: AzureSpringCloudQuickStart

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8

    - name: Clone Microservices Application Source Code
      uses: actions/checkout@v2-beta
      with:
        repository: 'Sneezry/piggymetrics'
        ref: 'zlhe/bugbash'
        path: 'piggymetrics'

    - name: Build Microservices Application
      run: |
        cd piggymetrics
        mvn clean package -D skipTests
          
    - name: Create Microservices
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.75
        inlineScript: |
          az extension add --name spring-cloud
          az configure --defaults group=zlhe-test
          az configure --defaults spring-cloud=zlhe-applens-bugbash
          az spring-cloud config-server git set --name zlhe-applens-bugbash --uri https://github.com/Sneezry/piggymetrics --label config
          az spring-cloud app create --name gateway
          az spring-cloud app create --name auth-service
          az spring-cloud app create --name account-service
          az spring-cloud app deploy -n gateway --jar-path $GITHUB_WORKSPACE/piggymetrics/gateway/target/gateway.jar
          az spring-cloud app deploy -n account-service --jar-path $GITHUB_WORKSPACE/piggymetrics/account-service/target/account-service.jar
          az spring-cloud app deploy -n auth-service --jar-path $GITHUB_WORKSPACE/piggymetrics/auth-service/target/auth-service.jar
          az spring-cloud app update -n gateway --is-public true
          az spring-cloud app show --name gateway | grep url
